export const WHATSAPP_TITLE = "WHATSAPP WEB";

export const SOCKET_STRINGS = {
 SUBSCRIBE : 'SUBSCRIBE', /** JOIN SOCKET CHANNEL */
 DISPATCH : 'DISPATCH', /** SEND REQUEST TO SERVER */ //receiveMessage
 ACKNOWLEDMENT : 'ACKNOWLEDMENT', /** RECEIVE RESPONSE FROM SERVER */
 UNSUBSCRIBE : 'UNSUBSCRIBE', /** LEAVE SOCKET CHANNEL */
 CHAT_HISTORY : 'CHATHISTORY', /** FETCH CHAT HISTORY OF A SELECTED USER */
}

export const SERVER_API = 'http://localhost:3001';